export const WEAPONS = {
  assault: {
    id: 'assault',
    name: 'Assault Rifle',
    damage: 22,
    fireRate: 0.1,
    magSize: 30,
    reserve: 120,
    reloadTime: 1.8,
    spread: 0.015,
    adsSpreadMult: 0.35,
    adsFov: 52,
    adsMoveMult: 0.75,
    pellets: 1,
    range: 120,
    automatic: true,
    color: 0x64748b,
    headshotMult: 2.0,
  },
  shotgun: {
    id: 'shotgun',
    name: 'Pump Shotgun',
    damage: 14,
    fireRate: 0.85,
    magSize: 8,
    reserve: 32,
    reloadTime: 2.4,
    spread: 0.12,
    adsSpreadMult: 0.55,
    adsFov: 62,
    adsMoveMult: 0.7,
    pellets: 8,
    range: 35,
    automatic: false,
    color: 0x78716c,
    headshotMult: 1.75,
  },
  sniper: {
    id: 'sniper',
    name: 'Bolt Sniper',
    damage: 95,
    fireRate: 1.4,
    magSize: 5,
    reserve: 20,
    reloadTime: 2.8,
    spread: 0.002,
    adsSpreadMult: 0.05,
    adsFov: 22,
    adsMoveMult: 0.45,
    pellets: 1,
    range: 200,
    automatic: false,
    color: 0x334155,
    headshotMult: 2.5,
  },
};

export const WEAPON_ORDER = ['assault', 'shotgun', 'sniper'];
